import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, Globe2, Home, MapPin, Plus, Search, ShieldCheck, Sparkles, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { countryConfigs, errandCategories, getCountryConfig } from "@/errand-config";

export const Route = createFileRoute("/errands")({ component: ErrandsPage });

type Errand = { id: number; title: string; category: string; location: string; price: number; status: string };
const seedErrands: Errand[] = [
  { id: 1, title: "Pick up groceries and deliver them", category: "Shopping", location: "Wuse, Abuja", price: 8500, status: "Open" },
  { id: 2, title: "Clean a 2-bedroom apartment", category: "House Chores", location: "Maitama, Abuja", price: 30000, status: "Open" },
  { id: 3, title: "Deliver documents to an office", category: "Run an Errand", location: "Central Area, Abuja", price: 7000, status: "Open" },
  { id: 4, title: "Weekly office cleaning", category: "Office Chores", location: "Garki, Abuja", price: 45000, status: "Open" },
];

function ErrandsPage() {
  const [country, setCountry] = useState("NG");
  const [category, setCategory] = useState("all");
  const [search, setSearch] = useState("");
  const [showPost, setShowPost] = useState(false);
  const [errands, setErrands] = useState(seedErrands);
  const config = getCountryConfig(country);
  const filtered = useMemo(() => errands.filter((e) => (category === "all" || e.category === category) && `${e.title} ${e.location}`.toLowerCase().includes(search.toLowerCase())), [errands, category, search]);
  function postErrand(form: FormData) {
    setErrands((items) => [{ id: Date.now(), title: String(form.get("title") || "New errand"), category: String(form.get("category") || "Other Tasks"), location: String(form.get("location") || "Local area"), price: Number(form.get("price") || 0), status: "Open" }, ...items]);
    setShowPost(false);
  }
  return <main className="min-h-screen bg-background">
    <header className="border-b border-gold/10 bg-card/40 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-gold"><Sparkles className="h-5 w-5" /></div><div><div className="font-display text-lg font-bold">Errand<span className="text-gradient-gold">Go</span></div><div className="text-xs text-muted-foreground">Global task marketplace</div></div></div><div className="flex items-center gap-2"><Link to="/dashboard"><Button variant="ghost">Dashboard</Button></Link><Button onClick={() => setShowPost(true)} className="bg-gradient-gold text-gold-foreground"><Plus className="mr-1 h-4 w-4" /> Post errand</Button></div></div></header>
    <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="grid gap-4 lg:grid-cols-[1.6fr_.9fr]"><div className="rounded-3xl border border-gold/15 bg-card p-6"><div className="flex items-center gap-2 text-xs font-semibold text-gold"><Globe2 className="h-4 w-4" /> WORK ANYWHERE</div><h1 className="mt-2 max-w-2xl font-display text-3xl font-bold sm:text-5xl">Get things done. <span className="text-gradient-gold">Get paid.</span></h1><p className="mt-3 max-w-2xl text-sm text-muted-foreground">Post errands and chores, or find nearby tasks and earn money. Currency, payment methods and supported languages adapt to the selected country.</p><div className="mt-6 grid gap-2 sm:grid-cols-3">{[["Post tasks","Describe the job, location, deadline and budget."],["Get matched","Workers choose tasks they can complete."],["Pay securely","Funds can be held until the task is accepted and completed."]].map(([a,b]) => <div key={a} className="rounded-2xl bg-muted/50 p-3"><div className="text-sm font-semibold">{a}</div><div className="mt-1 text-xs text-muted-foreground">{b}</div></div>)}</div></div>
      <div className="rounded-3xl border border-gold/15 bg-card p-5"><div className="flex items-center gap-2 font-semibold"><Globe2 className="h-5 w-5 text-gold" /> Your market</div><label className="mt-4 block text-xs text-muted-foreground">Country</label><select value={country} onChange={(e) => setCountry(e.target.value)} className="mt-1 w-full rounded-xl border bg-background px-3 py-2 text-sm">{countryConfigs.map((c) => <option key={c.code} value={c.code}>{c.name} ({c.symbol} {c.currency})</option>)}</select><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-muted p-3"><div className="text-muted-foreground">Currency</div><strong>{config.symbol} {config.currency}</strong></div><div className="rounded-xl bg-muted p-3"><div className="text-muted-foreground">Languages</div><strong>{config.languages.slice(0, 2).join(", ")}</strong></div></div><div className="mt-4 rounded-xl border border-gold/10 p-3 text-xs"><div className="font-semibold">Payment methods</div><div className="mt-1 text-muted-foreground">{config.paymentMethods.join(" • ")}</div></div></div></div>
      <div className="mt-8 flex flex-wrap gap-2"><Button variant={category === "all" ? "default" : "outline"} onClick={() => setCategory("all")}>All tasks</Button>{errandCategories.map((c) => <Button key={c.id} variant={category === c.label ? "default" : "outline"} onClick={() => setCategory(c.label)}>{c.label}</Button>)}</div>
      <div className="relative mt-4 max-w-xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search errands, chores or locations" className="w-full rounded-xl border bg-card py-3 pl-10 pr-3 text-sm" /></div>
      <div className="mt-6 grid gap-3 md:grid-cols-2">{filtered.map((errand) => <article key={errand.id} className="rounded-2xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-gold/10 px-2 py-1 text-[10px] font-semibold text-gold">{errand.category}</span><h2 className="mt-3 text-base font-bold">{errand.title}</h2></div><div className="text-right"><div className="text-lg font-bold">{config.symbol}{errand.price.toLocaleString()}</div><div className="text-[10px] text-muted-foreground">budget</div></div></div><div className="mt-4 flex items-center gap-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><MapPin className="h-3.5 w-3.5" />{errand.location}</span><span className="inline-flex items-center gap-1"><CheckCircle2 className="h-3.5 w-3.5" />{errand.status}</span></div><Button className="mt-4 w-full bg-gradient-gold text-gold-foreground">Accept task <ArrowRight className="ml-1 h-4 w-4" /></Button></article>)}</div>
      <div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-card p-4"><WalletCards className="h-5 w-5 text-gold" /><div className="mt-2 font-semibold">Wallet & deposits</div><div className="mt-1 text-xs text-muted-foreground">Top up in local currency and use a protected balance for tasks.</div></div><div className="rounded-2xl border bg-card p-4"><ShieldCheck className="h-5 w-5 text-gold" /><div className="mt-2 font-semibold">Trust & safety</div><div className="mt-1 text-xs text-muted-foreground">Identity verification, ratings, reports and dispute handling.</div></div><div className="rounded-2xl border bg-card p-4"><Home className="h-5 w-5 text-gold" /><div className="mt-2 font-semibold">Home & office</div><div className="mt-1 text-xs text-muted-foreground">Cleaning, laundry, organization, office support and permitted local services.</div></div></div>
    </section>
    {showPost && <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><form action={postErrand} className="w-full max-w-lg rounded-2xl bg-card p-6 shadow-xl"><h2 className="text-xl font-bold">Post an errand</h2><p className="mt-1 text-xs text-muted-foreground">Your selected market: {config.name} · {config.symbol}</p><input name="title" required placeholder="What do you need done?" className="mt-5 w-full rounded-xl border bg-background p-3 text-sm" /><select name="category" className="mt-2 w-full rounded-xl border bg-background p-3 text-sm"><option>Run an Errand</option><option>House Chores</option><option>Office Chores</option><option>Shopping</option><option>Moving & Help</option><option>Other Tasks</option></select><input name="location" required placeholder="Location" className="mt-2 w-full rounded-xl border bg-background p-3 text-sm" /><input name="price" required type="number" min="1" placeholder={`Budget in ${config.currency}`} className="mt-2 w-full rounded-xl border bg-background p-3 text-sm" /><div className="mt-4 flex gap-2"><Button type="button" variant="outline" onClick={() => setShowPost(false)} className="flex-1">Cancel</Button><Button type="submit" className="flex-1 bg-gradient-gold text-gold-foreground">Post task</Button></div></form></div>}
  </main>;
}
