import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, CheckCircle2, Globe2, Home, MapPin, Plus, Search, ShieldCheck, Sparkles, WalletCards } from 'lucide-react';
import { countryConfigs, errandCategories, getCountryConfig } from './errand-config';
import './styles.css';

type Errand = { id:number; title:string; category:string; location:string; price:number; status:string };
const seed:Errand[] = [
 {id:1,title:'Pick up groceries and deliver them',category:'Shopping',location:'Wuse, Abuja',price:8500,status:'Open'},
 {id:2,title:'Clean a 2-bedroom apartment',category:'House Chores',location:'Maitama, Abuja',price:30000,status:'Open'},
 {id:3,title:'Deliver documents to an office',category:'Run an Errand',location:'Central Area, Abuja',price:7000,status:'Open'},
 {id:4,title:'Weekly office cleaning',category:'Office Chores',location:'Garki, Abuja',price:45000,status:'Open'}
];

function App(){
 const [country,setCountry]=useState('NG'); const [category,setCategory]=useState('all'); const [search,setSearch]=useState(''); const [post,setPost]=useState(false); const [errands,setErrands]=useState(seed); const [wallet,setWallet]=useState(0); const config=getCountryConfig(country);
 const filtered=useMemo(()=>errands.filter(e=>(category==='all'||e.category===category)&&`${e.title} ${e.location}`.toLowerCase().includes(search.toLowerCase())),[errands,category,search]);
 function add(form:FormData){setErrands(x=>[{id:Date.now(),title:String(form.get('title')),category:String(form.get('category')),location:String(form.get('location')),price:Number(form.get('price')),status:'Open'},...x]);setPost(false)}
 return <div className="app">
  <header><div className="brand"><span className="logo"><Sparkles size={19}/></span><div><b>Errand<span>Go</span></b><small>Global task marketplace</small></div></div><nav><a href="#tasks">Find tasks</a><a href="#how">How it works</a><button className="outline" onClick={()=>setPost(true)}><Plus size={16}/> Post errand</button></nav></header>
  <section className="hero"><div className="hero-copy"><div className="eyebrow"><Globe2 size={15}/> WORK ANYWHERE</div><h1>Get things done.<br/><em>Get paid.</em></h1><p>ErrandGo connects people who need everyday tasks completed with trusted people ready to earn. Run errands, handle house chores, support offices and more.</p><div className="hero-actions"><button className="primary" onClick={()=>setPost(true)}>Post an errand <ArrowRight size={17}/></button><a className="secondary" href="#tasks">Find work</a></div><div className="trust"><CheckCircle2 size={16}/> Local pricing • Secure task payments • Ratings & reviews</div></div>
   <div className="market"><div className="market-title"><Globe2 size={19}/> Your market</div><label>Country</label><select value={country} onChange={e=>setCountry(e.target.value)}>{countryConfigs.map(c=><option value={c.code} key={c.code}>{c.name} ({c.symbol} {c.currency})</option>)}</select><div className="stats"><div><small>Currency</small><strong>{config.symbol} {config.currency}</strong></div><div><small>Languages</small><strong>{config.languages.slice(0,2).join(', ')}</strong></div></div><div className="payments"><b>Available payment methods</b><span>{config.paymentMethods.join(' • ')}</span></div><button className="wallet" onClick={()=>setWallet(w=>w+10000)}><WalletCards size={17}/> Demo wallet: {config.symbol}{wallet.toLocaleString()} <small>+ add funds</small></button></div></section>
  <section className="how" id="how"><div><span>01</span><b>Post a task</b><p>Describe what you need, where it is and your budget.</p></div><div><span>02</span><b>Choose a worker</b><p>Review available people, ratings and task details.</p></div><div><span>03</span><b>Complete & pay</b><p>Confirm completion and release the agreed payment.</p></div></section>
  <section className="tasks" id="tasks"><div className="section-head"><div><div className="eyebrow">LOCAL OPPORTUNITIES</div><h2>Find an errand</h2></div><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tasks or locations"/></div></div><div className="chips"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>All</button>{errandCategories.map(c=><button className={category===c.label?'active':''} onClick={()=>setCategory(c.label)} key={c.id}>{c.label}</button>)}</div><div className="grid">{filtered.map(e=><article key={e.id}><div className="card-top"><div><span className="tag">{e.category}</span><h3>{e.title}</h3></div><div className="price">{config.symbol}{e.price.toLocaleString()}<small>budget</small></div></div><div className="meta"><span><MapPin size={14}/>{e.location}</span><span><CheckCircle2 size={14}/>{e.status}</span></div><button className="accept">Accept task <ArrowRight size={15}/></button></article>)}</div></section>
  <section className="features"><div><WalletCards/><h3>Wallet & deposits</h3><p>Country-aware balances for task payments and future payouts.</p></div><div><ShieldCheck/><h3>Trust & safety</h3><p>Build confidence with verification, ratings, reports and disputes.</p></div><div><Home/><h3>Home & office</h3><p>Cleaning, laundry, organization, delivery and permitted local services.</p></div></section>
  <footer><b>ErrandGo</b><span>Global errands. Local opportunities.</span><span>© 2026 ErrandGo</span></footer>
  {post&&<div className="modal"><form onSubmit={e=>{e.preventDefault();add(new FormData(e.currentTarget))}}><h2>Post an errand</h2><p>Market: {config.name} · {config.currency}</p><input name="title" required placeholder="What do you need done?"/><select name="category"><option>Run an Errand</option><option>House Chores</option><option>Office Chores</option><option>Shopping</option><option>Moving & Help</option><option>Other Tasks</option></select><input name="location" required placeholder="Location"/><input name="price" required type="number" min="1" placeholder={`Budget in ${config.currency}`}/><div className="form-actions"><button type="button" className="outline" onClick={()=>setPost(false)}>Cancel</button><button className="primary">Publish task</button></div></form></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
